version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
